version: '3.8'
services:
  db:
    image: postgres:16-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHANGEINPRODUCTION
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  play:
    image: cloudbox
    build:
      dockerfile: Dockerfile
    volumes:
      - /srv/credentials/google_bucket_oauth.json:/srv/credentials/google_bucket_oauth.json
    user: "1000:1000"
    ports:
      - '9000:9000'
    links:
      - "db"
    depends_on:
      - db

volumes:
  db:
    driver: local