version: '3.8'
services:
  db:
    image: postgres:16-alpine3.17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHANGEINPRODUCTION
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  play:
    image: testserver
    links:
      - "db"
    build:
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - db

volumes:
  db:
    driver: local