version: '3.8'
services:

  play:
    image: animalprotect
    environment:
      - POSTGRES_DB_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_BUCKET_NAME=${GOOGLE_BUCKET_NAME}
      - GOOGLE_CREDENTIALS_FILE_PATH=${GOOGLE_CREDENTIALS_FILE_PATH}
    build:
      dockerfile: Dockerfile
    volumes:
      - /srv/credentials/google_bucket_oauth.json:/srv/credentials/google_bucket_oauth.json
    user: "1000:1000"
    ports:
      - '9000:9000'
