name: imageRecognitionAppAction
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'imageRecognitionApp/**'
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./imageRecognitionApp
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |        
            .github
            imageRecognitionApp
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
         node-version: 20.x
         cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: build js files
        run: npm run build
      - name: Format check
        run: npm run lint
      - name: Run tests
        run: npm run test