name: imageRecognitionAppAction
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'imageRecognitionApp/**'
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: imageRecognitionApp
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |        
            .github
            imageRecognitionApp
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
         node-version: 18.x
         cache: 'npm'
         cache-dependency-path: 'imageRecognitionApp/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: build js files
        run: npm run build
      - name: Format check
        run: npm run lint:ci
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          # used https://cloud.google.com/vision/docs/base64?hl=de#linux to create b64 encoded from oauth.json
          credentials_json: '${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}'
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west3-docker.pkg.dev
          project_id: spring-monolith-403010/animalprotect-docker-repo
          image_name: imagerecognitionapp
          image_tag: latest,v2
          context: ./imageRecognitionApp