name: qualityChecks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 21

      - name: scalafmt check
        run: sbt scalafmtCheck

      - name: Run sbt Tests
        run: sbt test
